name: test

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=test
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongo_test_data:/data/db

volumes:
  mongo_test_data:
