name: deploy-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy files to production server
        uses: appleboy/scp-action@master
        with:
          host: 13.232.133.202
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: /home/ubuntu/test-deploy

      - name: Run commands on production server
        uses: appleboy/ssh-action@master
        with:
          host: 13.232.133.202
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/test-deploy
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
