name: Deploy to Railway

on:
  push:
    branches:
      - main  # Or your default branch name (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy to Railway
        run: railway up --service <your-service-name>
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
